sudo: required
services:
    - docker

before_install:
    - docker build -t kissta/dockertokuj -f Dockerfile.dev .

script:
    - docker run -e CI=true kissta/dockertokuj npm run test

deploy:
    edge: true 
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "dockertokuj"
    env: "Dockertokuj-env"
    bucket_name: "elasticbeanstalk-us-east-2-233080411415"
    bucket_path: "dockertokuj"
    on:
      branch: master
    access_key_id: 
      secure: $AWS_ACCESS_KEY
    secret_access_key: 
      secure: "$AWS_SECRET_KEY"